####################################################################
# ANSIBLE LINK CONFIGURATION                                       #
# docs:                                                            #
#   github.com/lfkdev/ansible-link                                 #
#   ansible-runner.readthedocs.io/_/downloads/en/stable/pdf/       #
####################################################################

# flask
host: '127.0.0.1'
port: 5001
debug: false

# ansible-runner
suppress_ansible_output: false
omit_event_data: false
only_failed_event_data: false

# general
playbook_dir: '/etc/ansible/'
inventory_file: '/etc/ansible/environments/hosts'
job_storage_dir: '/var/lib/ansible-link/job-storage'
log_level: 'INFO'

# ansible-link
playbook_whitelist: []
# playbook_whitelist:
#   - monitoring.yml
#   - mariadb.yml