name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-link-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create config file
      run: |
        echo "playbook_dir: ./test_playbooks" > ansible_link/config.yml
        echo "inventory_file: ./test_inventory.ini" >> ansible_link/config.yml
        echo "job_storage_dir: ./test_job_storage" >> ansible_link/config.yml
        mkdir -p test_playbooks test_job_storage
        touch test_inventory.ini
    - name: Create test playbook
      run: |
        cat << EOF > test_playbooks/test_playbook.yml
        ---
        - name: Test Playbook
          hosts: localhost
          connection: local
          tasks:
            - name: Print a message
              debug:
                msg: "This is a test playbook"
        EOF
    - name: Set PYTHONPATH and ANSIBLE_API_CONFIG
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "ANSIBLE_API_CONFIG=$GITHUB_WORKSPACE/ansible_link/config.yml" >> $GITHUB_ENV
    - name: Show structure and environment
      run: |
        ls -R
        echo "PYTHONPATH: $PYTHONPATH"
        echo "ANSIBLE_API_CONFIG: $ANSIBLE_API_CONFIG"
        pip list
        cat test_playbooks/test_playbook.yml
    - name: Update import in ansible_link.py
      run: |
        sed -i 's/from webhook import WebhookSender/from ansible_link.webhook import WebhookSender/' ansible_link/ansible_link.py
    - name: Run tests
      run: |
        python -m unittest discover tests