host: '127.0.0.1'
port: 5001
debug: false

playbook_dir: '/etc/ansible/'
inventory_dir: '/etc/ansible/hosts'
ansible_playbook_cmd: 'ansible-playbook'

job_storage_dir: '/var/lib/ansible-link/job-storage'

log_level: 'INFO'
log_file: '/var/log/ansible-link/api.log'

playbook_whitelist:
  - monitoring_stack.yml
